@@include('../libs/jquery/dist/jquery.js')
@@include('../libs/jquery-mousewheel/jquery.mousewheel.js')
@@include('../libs/slick-1.6.0/slick/slick.js')
@@include('../libs/velocity/velocity.js')
@@include('../libs/perfect-scrollbar/js/perfect-scrollbar.jquery.js')
@@include('../libs/fancybox/dist/jquery.fancybox.js')
@@include('../libs/jquery.maskedinput/dist/jquery.maskedinput.js')
@@include('../libs/highlight/build/highlight.pack.js')

/* jQuery UI */
@@include('../libs/jquery-ui/ui/version.js')
@@include('../libs/jquery-ui/ui/safe-active-element.js')
@@include('../libs/jquery-ui/ui/escape-selector.js')
@@include('../libs/jquery-ui/ui/form.js')
@@include('../libs/jquery-ui/ui/widget.js')
@@include('../libs/jquery-ui/ui/position.js')
@@include('../libs/jquery-ui/ui/form-reset-mixin.js')
@@include('../libs/jquery-ui/ui/keycode.js')
@@include('../libs/jquery-ui/ui/labels.js')
@@include('../libs/jquery-ui/ui/unique-id.js')
@@include('../libs/jquery-ui/ui/ie.js')
@@include('../libs/jquery-ui/ui/data.js')
@@include('../libs/jquery-ui/ui/plugin.js')
@@include('../libs/jquery-ui/ui/safe-blur.js')
@@include('../libs/jquery-ui/ui/scroll-parent.js')
@@include('../libs/jquery-ui/ui/widgets/menu.js')
@@include('../libs/jquery-ui/ui/widgets/selectmenu.js')
@@include('../libs/jquery-ui/ui/widgets/mouse.js')
@@include('../libs/jquery-ui/ui/widgets/draggable.js')
@@include('../libs/jquery-ui/ui/widgets/slider.js')
/* ========= */

$(document).ready(function () {
    @@include('../libs/goodshare/goodshare.min.js')
});